### PR TITLE
Updated theme similar to main website

### PR DESCRIPTION
**Pull request by Rajkumar-stackcoder**
## Updated theme and solved issue #3 
- Added some responsive style
- Added background image
- Added modified the existing refresh method

### CODE REVIEW

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by harikanani — APPROVED** [review]
LGTM 👍

**Comment by Rajkumar-stackcoder** [comment]
This is the Image of Changes
Screenshot 2021-10-02 163340

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM ✅

**Comment by kamleshjoshi8102** [comment]
@Rajkumar-stackcoder Can you share link of this game hosted on github pages

**Comment by Rajkumar-stackcoder** [comment]
> @Rajkumar-stackcoder Can you share link of this game hosted on github pages

hi @kamleshjoshi8102  i dont have this pr link 
but u can check this  https://rajkumar-stackcoder.github.io/Dice_Game/
this is the same footer is different

**Comment by Rajkumar-stackcoder** [comment]
> 
> 
> @Rajkumar-stackcoder Can you share link of this game hosted on github pages

changes in link https://rajkumar-stackcoder.github.io/Dice_Game/

**Comment by adityamangal1** [comment]
@Rajkumar-stackcoder I'm not able to change the name of the players. Haven't you add that functionality or there is some other issue?

**Comment by Rajkumar-stackcoder** [comment]
> Hey @Rajkumar-stackcoder, I'm not able to change the name of the players. Haven't you add that functionality or there is some other issue?
I have not add that functionality

**Pull request merged**
