### PR TITLE
Added Name Feature & No Need To Reload Every Time

### PR DESCRIPTION
**Pull request by fenil3357**
Added a name feature so players can enter their names.
Also upgraded some javascript code sono need to reload the page everytime.
Added a button to change the names of the player.
At last added some css for these buttons.

### CODE REVIEW

**Comment by kamleshjoshi8102** [comment]
> Added a name feature so players can enter their names. Also upgraded some javascript code sono need to reload the page everytime. Added a button to change the names of the player. At last added some css for these buttons.

Can you add ScreenShot of your page hosted locally or on the GitHub page?

**Review by kevalvavaliya — APPROVED** [review]
LGTM

**Review by adityamangal1 — APPROVED** [review]

**Comment by fenil3357** [comment]
> > Added a name feature so players can enter their names. Also upgraded some javascript code sono need to reload the page everytime. Added a button to change the names of the player. At last added some css for these buttons.
> 
> Can you add ScreenShot of your page hosted locally or on the GitHub page?

Annotation 2021-10-01 173345

**Review by harikanani — APPROVED** [review]
Thanks for your contribution :)

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM ✅✅

**Comment by adityamangal1** [comment]
@all-contributors please add @fenil3357  for code contribution

**Pull request merged**
