### PR TITLE
[Feat]: Updated Fav icon

### PR DESCRIPTION
**Pull request by dhruvaop**
Screenshot (144)
In the Dicee updated BG logo

### CODE REVIEW

**Review by adityamangal1 — CHANGES_REQUESTED** [review]
Hey, @dhruvaop this is a dice game so there is no need to upload BG Icon. Upload something related to game.

**Comment by dhruvaop** [comment]
Dice
images
Which one should I choose

**Comment by adityamangal1** [comment]
> Dice images Which one should I choose

Upto you. No need to send here just try both

**Review by adityamangal1 — APPROVED** [review]

**Comment by adityamangal1** [comment]
@all-contributors please add @dhruvaop for code contribution

**Pull request merged**
